sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo pip install codecov # From https://github.com/travis-ci/travis-ci/issues/1705

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
  # - sudo apt-get install witty-dev
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - libboost1.55-all-dev

before_script: 
  - ./download_other_githubs.sh

script: 
  - ./build_console.sh
  - ./build_desktop.sh
  # - ./build_website.sh
  - ./AsciiArterConsole --about
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)

