sudo: required
language: cpp
compiler: gcc
dist: xenial

before_install:
  - sudo pip install codecov

install: 
  - ./install_oclint.sh

addons:
  apt:
    sources:
    - boost-latest
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev

before_script: 
  - ./download_other_githubs.sh

script: 
  - qmake PaperRockScissorsConsole.pro
  - make --silent
  - qmake PaperRockScissorsDesktop.pro
  - make --silent
  - ./PaperRockScissorsConsole --about
  - ./get_code_cov.sh
  - codecov
  - ./do_oclint.sh

after_success: 
  - bash <(curl -s https://codecov.io/bash)
